- title: "Character Building in the Martial Arts"
  blurb: "The purpose of life is not to be happy. It is to be useful, to be honorable, to be compassionate, to have it make some difference that you have lived and lived well ..."
  content: |
    The purpose of life is not to be happy. It is to be useful, to be honorable, to be compassionate, to have it make some difference that you have lived and lived well. Ralph Waldo Emerson
    <br>
    Warriors seek to show BENEVOLENCE each and every day: that is, to take care of those around us. By seeking to do what is fair and good for others, you will often find a happiness that cannot be brought about by anything else.
    <br>
    It may seem our focus on character building is irrelevant when it comes to bringing a child up to Black Belt level, however our belief is that in order to be a true Black Belt in any art, one must have a value system behind the skills they learn.
    <br>
    Someone who learns to fight without a value system can easily turn from being a warrior to a bully.
    <br>
    It is because of this that we have such a strong focus on making our students not simply good martial artists, but great leaders, in the hope that our future will be led by strong and benevolent men and women someday!
  headerImageUrl: "https://aethercode-btbmartialarts.s3.amazonaws.com/assets/Articles/58d53f15c765a.jpg"

- title: "What Are Mat Chats?"
  blurb: "When your kids are in class, you'll see them sitting and listening to their instructor talking (sometimes for what seems like a while!) during a section of class."
  content: | 
    When your kids are in class, you'll see them sitting and listening to their instructor talking (sometimes for what seems like a while!) during a section of class.
    <br>
    These sit downs are called 'Mat Chats', and while it may look like simply a break from drilling, we believe these talks are one of the most important parts of class!
    <br>
    During Mat Chats, instructors will discuss topics ranging from street safety, self confidence, how to help others, showing respect, how to deal with bullies vs. strangers, and conflict resolution, just to name a few.
    <br>
    As we tell the kids, being a warrior is not just about punches and kicks, but about knowing why we do what we do, when to do it, and knowing how to demonstrate the character of a warrior.
    If you can, ask your child about what was discussed in their classes as these talks are a huge part in their journey to black belt.
    <br>
    It is our goal to not simply teach your child to 'do martial arts', but to make them a leader of the future, equipped with not only the physical, but mental tools needed to make a difference in the world as they grow and mature!
  headerImageUrl: "https://aethercode-btbmartialarts.s3.amazonaws.com/assets/Articles/58d53f90ddb6d.jpg"

- title: "Evaluation Preparation Materials"
  blurb: | 
    We are always looking for new ways to help students get ready for their evaluations.
    For technique preparation, please head on over to our Education Resources videos, found at our Youtube Channel below!`,
  content: |
    <p><br></p>
    <p>
      <a href="https://www.youtube.com/channel/UCJTl1jsRHBzGlmwfzUApNHw" data-mce-href="https://www.youtube.com/channel/UCJTl1jsRHBzGlmwfzUApNHw">Beyond the Belt: Education Resources</a>
      <br>
    </p>
    <p><br></p>
    <h3>
      Advanced Techniques Quiz (Purple Belt & Up): <a href="https://s3.amazonaws.com/aethercode-btbmartialarts/assets/WEBSITE+Advanced+Techniques+Quiz.pdf" target="_blank">click here</a>
    </h3>
    <h3>
      Beginner Techniques Quiz (White Belt & Up): <a href="https://s3.amazonaws.com/aethercode-btbmartialarts/assets/WEBSITE+Beginner+Technique+Quiz.pdf" target="_blank">click here</a>
    </h3>
  headerImageUrl: "https://aethercode-btbmartialarts.s3.amazonaws.com/assets/Articles/5ae75ffdbfe47.jpg"