content: |
  <ul class="social-links circle small clearfix hidden-xs">
    <li class="twitter"><a target="_blank" href="http://www.twitter.com"><i class="fa fa-twitter"></i></a></li>
    <li class="linkedin"><a target="_blank" href="http://www.linkedin.com"><i class="fa fa-linkedin"></i></a></li>
    <li class="googleplus"><a target="_blank" href="http://plus.google.com"><i class="fa fa-google-plus"></i></a></li>
    <li class="youtube"><a target="_blank" href="http://www.youtube.com"><i class="fa fa-youtube-play"></i></a></li>
    <li class="facebook"><a target="_blank" href="http://www.facebook.com/beyond.the.belt"><i class="fa fa-facebook"></i></a></li>
  </ul>
  <ul class="list-inline hidden-sm hidden-xs">
    <li><i class="fa fa-map-marker pr-5 pl-10"></i>77 Court St. Laconia</li>
    <li><i class="fa fa-map-marker pr-5 pl-10"></i>12B Main St. Center Harbor</li>
    <li><i class="fa fa-phone pr-5 pl-10"></i>(603) 366-1044</li>
  </ul>