- title: "Kids Martial Arts Leadership"
  blurb: "The program is for kids ages 4-16 (4 and 5 year olds receive separate instruction). It is based on participation twice a week, but with multiple class times that fit your schedule. Classes are 45 minutes long."
  content: |
    <p>
      At Beyond the Belt's Martial Arts Leadership Program, we go far beyond kicking and punching. We focus on character building, and school and street safety. Students learn practical martial arts and gain skills in an 
      encouraging environment. We use goal setting as a key to the child’s success, and each student gets individual attention, gets challenged, and gets encouraged. 
      <br><br>
      The course focuses around exercises, mat chats, and martial arts training.
      <br><br>
      <strong><u>Exercise:</u></strong>
      <br><br>
      Each child works on their physical goals for push-ups, crunches, and squats. The focus is on form and doing the exercise well (Habits we train are habits we gain!). Each student is encouraged to set their own goals 
      and exceed them. 
      <br><br>
      <strong><u>Mat Chats</u></strong>
      <br><br>
      Mat chats are inspirational talks given in each class. The 1st part of a mat chat is always about character development, including self discipline (doing what you know you're supposed to, even if you don't want to), 
      positive attitudes (having a "whatever it takes attitude," an "attitude of gratitude", etc.), and more. The focus is on training the mind as well as the body.
      <br><br>
      The second part of a mat chat is around school safety and life skills. This includes the ABCs of conflict (how to Avoid, how to Be calm, and how to Communicate), stranger danger, and other street safety topics. Life 
      skills are also imparted such as how to greet people, make friends, and have good interaction skills that breed confidence.
      <br><br>
      <strong><u>Martial Arts Training:</u></strong>
      <br><br>
      Each week consists of a different focus in a rotating curriculum to help maximize learning potential for each student.<br><br><strong>At a beginner level,</strong> students are learning basics such as punching, 
      kicking techniques, basic defense, and bag work. During this phase, they are being taught how to work well with others , how to use their strengths to help others weaknesses, and above all, they are working on their 
      ability to focus!
      <br><br>
      Once a student has graduated the beginner program, they move to the&nbsp;<strong>advanced classes</strong>. These classes teach ground defense, improved technique, and more advanced partner drills. Students are 
      taught to hone their leadership skills and pursue martial arts with excellence.
      <br><br>
      The program is for kids ages 4-16 (4 and 5 year olds receive separate instruction). It is based on participation twice a week, but with multiple class times that fit your schedule. Classes are 45 minutes long. 
      <br><br>
      We pride ourselves on providing a safe, welcoming, and encouraging environment and making a positive impact on young people through teaching martial arts.
      <br><br>
      Come join us! Give us a call at 366.1044 to schedule a personal tour of the facility and meet our staff. Come find out if this program could help your child build self confidence, gain new skills, and develop character.
      <br>
    </p>
  headerImageUrl: "https://aethercode-btbmartialarts.s3.amazonaws.com/assets/Articles/56f474804c6a0.jpg"

- title: "Adult Mixed Martial Arts"
  blurb: "Become belt ranked in our Adult Mixed Martial Arts Program! Learn mixed martial arts in a family friendly environment that encourages teamwork and core values in training. Get started TODAY!"
  content: |
    <p class="p1">
      Beyond the Belt's Adult Mixed Martial Arts is unlike any other mixed martial arts program. Discover technique and intense training with a traditional mindset of honor and respect! Learn practical martial arts skills, 
      perfect technique, and discover what it truly means to be a black belt!
    <\/p>
    <p class="p2">
      Students are encouraged to make at least one Stand Up/MMA class and one Grappling class per week. Each week has a set curriculum that is diverse in material, ranging from mitt work, ground and pound, kicking, punching, 
      sparring, grappling, etc.
      <br>
    <\/p>
    <p class="p2">
      We pride ourselves on providing a mixed martial arts training facility that is clean, safe, and centered about self betterment and teamwork in a world of often very\u0026nbsp;self centered martial arts practitioners.
      <br>
    <\/p>
    <p class="p2">
      Are you ready to achieve Black Belt level? Give us a call at 603.366.1044 today and find out more about how to enroll as a student with Beyond the Belt's Adult Mixed Martial Arts Program!
      <br>
    </p>
  headerImageUrl: "https://aethercode-btbmartialarts.s3.amazonaws.com/assets/Articles/17/5633e3b4c6294.jpg"