header: "Weekly <strong>Class Schedules</strong>"
intro: "<p></p>"
days:
  - name: Monday
    classes: |
      <span class="bg-aqua small"><strong>4p-4:45p</strong> Advanced Junior</span>
      <span class="bg-purple small"><strong>4p-4:45p</strong> Beginner Junior</span>
      <span class="bg-red small"><strong>4:45p-5:30p</strong> Black Belt Club</span>
      <span class="bg-purple small"><strong>4:45p-5:30p</strong> Beginner/Advanced Teen class</span>
      <span class="bg-aqua small"><strong>5:30p-6:15p</strong> Advanced Junior</span>
      <span class="bg-blue small"><strong>5:30p-6:15</strong> Junior Teen</span>
      <span class="bg-orange small"><strong>6:15p-7p</strong> Beginner / Advanced Teen</span>
      <span class="bg-navy small"><strong>7:30p-8:30p</strong> Adult Mixed Martial Arts</span>
  - name: Tuesday
    classes: |
      <span class="bg-purple small"><strong>4p-4:45p</strong> Beginner Junior</span>
      <span class="bg-blue small"><strong>4:45p-5:30</strong> Junior Teen</span>
      <span class="bg-aqua small"><strong>4:45p-5:30p</strong> Advanced Junior</span>
      <span class="bg-purple small"><strong>5:30p-6:15p</strong> Beginner Junior</span>
      <span class="bg-orange small"><strong>5:30p-6:15p</strong> Beginner / Advanced Teen</span>
      <span class="bg-red small"><strong>6:15p-7p</strong> BTB Teen Elite</span>
      <span class="bg-navy small"><strong>6:15p-7p</strong> Adult Mixed Martial Arts</span>
  - name: Wednesday
    classes: |
      <span class="bg-aqua small"><strong>4p-4:45p</strong> Advanced Junior</span>
      <span class="bg-orange small"><strong>4:45p-5:30p</strong> Beginner / Advanced / Elite Teen</span>
      <span class="bg-aqua small"><strong>5:30p-6:30p</strong> Advanced Junior</span>
      <span class="bg-blue small"><strong>5:30p-6:15p</strong> Junior Teen</span>
      <span class="bg-orange small"><strong>6:15p-7p</strong> Beginner / Advanced Teen</span>
      <span class="bg-navy small"><strong>6:15p-7p</strong> Adult Mixed Martial Arts</span>
  - name: Thursday
    classes: |
      <span class="bg-purple small"><strong>4p-4:45p</strong> Beginner Junior</span>
      <span class="bg-blue small"><strong>4:45p-5:30</strong> Junior Teen</span>
      <span class="bg-aqua small"><strong>4:45p-5:30p</strong> Advanced Junior</span>
      <span class="bg-purple small"><strong>5:30p-6:15p</strong> Beginner Junior</span>
      <span class="bg-orange small"><strong>5:30p-6:15p</strong> Beginner / Advanced Teen</span>
      <span class="bg-red small"><strong>6:15p-7p</strong> BTB Teen Elite</span>
      <span class="bg-navy small"><strong>7p-8p</strong> Adult Mixed Martial Arts</span>
  - name: Friday
    classes: |
      <span class="bg-aqua small"><strong>5:30p-6:15p</strong> Advanced Junior</span>
      <span class="bg-orange small"><strong>6:15-7p</strong> All Levels Teen</span>
